version: '3.3'

services:

  ###################
  # Shared Services #
  ###################

  # mongo:
  #   image: mongo:4
  #   restart: always
  #   command: --smallfiles
  #   expose:
  #     - 27017
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo_data_vol:/data/db
  

  pubgate:
    build: .
    image: pubgate
    restart: always
    command: invoke server
    environment:
      - SHELL=/bin/sh
      - DEBUG=true
    ports:
       - 8888:8000
    volumes:
      - type: bind
        source: ./
        target: /code/
    # stop_signal: SIGINT