version: '3.7'

services:

  mongo:
     image: mongo:4
     restart: always
#     command: --smallfiles
#     volumes:
#       - mongo_data_vol:/data/db

  pubgate:
    build: .
    image: pubgate
    restart: always
    ports:
       - 8000:8000
    volumes:
      - type: bind
        source: ./
        target: /code/
    # stop_signal: SIGINT
    environment:
      - MONGODB_HOST=mongo
      - DOMAIN=$domain